server:
  port: 8080
spring:
  kafka:
    producer:
      bootstrap-servers: 'localhost:9000'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping: "ad:eu.pontsystems.adsproducer.model.Ad"
kafka:
  topic:
    name: ads